    <script src="{{asset('frontend/js/jquery-1.12.4.minb8ff.js?ver=1.12.4') }}"></script>
	<script src="{{asset('frontend/js/jquery-ui-1.12.4.minb8ff.js?ver=1.12.4') }}"></script>
	<script src="{{asset('frontend/js/bootstrap.min.js') }}"></script>
	<script src="{{asset('frontend/js/jquery.flexslider.js') }}"></script>
	<script src="{{asset('frontend/js/chosen.jquery.min.js') }}"></script>
	<script src="{{asset('frontend/js/owl.carousel.min.js') }}"></script>
	<script src="{{asset('frontend/js/jquery.countdown.min.js') }}"></script>
	<script src="{{asset('frontend/js/jquery.sticky.js') }}"></script>
	<script src="{{asset('frontend/js/functions.js') }}"></script>